# Generated by Selenium IDE
import pytest
from barancev_programmirovanie.group import Group
from barancev_programmirovanie.application import Application


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


def test_add_group(app):
    app.login(username='admin', password='secret')
    app.create_group(Group(name='first', header='second', footer='thirth'))
    app.logout()


def test_add_empty_group(app):
    app.login(username='admin', password='secret')
    app.create_group(Group(name='', header='', footer=''))
    app.logout()


if __name__ == "__main__":
    unittest.main()
